from typing import IO

class Image:
    @classmethod
    def new(cls, mode: str, size: tuple[int, int]) -> Image: ...
    @classmethod
    def alpha_composite(cls, image1: Image, image2: Image) -> Image: ...
    def paste(self, image: Image, location: tuple[int, int]) -> Image: ...
    @property
    def height(self) -> int: ...
    @property
    def width(self) -> int: ...
    @classmethod
    def open(cls, file: IO) -> Image: ...
    def resize(self, size: tuple[int, int]) -> Image: ...
    @property
    def size(self) -> tuple[int, int]: ...
    def save(
        self,
        IO,
        format: str,
        save_all: bool,
        append_images: list[Image],
        loop: int,
        duration: int,
    ) -> None: ...
    def convert(self, mode: str): ...
